### PR TITLE
New KNFG

### PR DESCRIPTION
**Pull request by JcFl4**
Added taxi lines, gates, roadways and much more.

### CODE REVIEW

**Comment by JcFl4** [comment]
I had trouble uploading, any "New KNFG" is the right file.

**Comment by carmichaelalonso** [comment]
Nice job @JcFl4 - looks much better! Merging...

**Comment by carmichaelalonso** [comment]
I just made one change to the ATC frequencies and their naming (required for next update) :)

**Comment by JcFl4** [comment]
OK! Looking forward to the next update!!

**Pull request merged**
